# Generated by Django 2.2.4 on 2020-01-05 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0002_auto_20200105_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 16, 37, 52, 72725, tzinfo=utc)),
        ),
    ]
