# Generated by Django 2.2.4 on 2020-01-05 21:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0005_auto_20200105_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 21, 22, 14, 279860, tzinfo=utc)),
        ),
    ]
